http:
  routers:
    gateway:
      rule: "Host(`personal-financial.duckdns.org`) && PathPrefix(`/api`)"
      entryPoints: [websecure]
      service: gateway
      tls:
        certResolver: myresolver
    swagger:
      rule: "Host(`personal-financial.duckdns.org`) && (PathPrefix(`/swagger-ui`) || Path(`/swagger-ui.html`) || PathPrefix(`/v3/api-docs`) || PathPrefix(`/webjars`))"
      entryPoints: [websecure]
      service: gateway
      tls:
        certResolver: myresolver
    grafana:
      rule: "Host(`personal-financial.duckdns.org`) && PathPrefix(`/grafana`)"
      entryPoints: [websecure]
      service: grafana
      tls:
        certResolver: myresolver
    frontend:
      rule: "Host(`personal-financial.duckdns.org`)"
      entryPoints: [websecure]
      service: frontend
      tls:
        certResolver: myresolver
  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://gateway:8080"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
